"""create sequences sequence_steps email_messages and workspace webhook_token

Revision ID: 08a9895e1505
Revises: 5a977d8b9a4b
Create Date: 2026-08-05 13:38:18.695478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08a9895e1505'
down_revision: Union[str, None] = '5a977d8b9a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trigger', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sequences_workspace_id'), 'sequences', ['workspace_id'], unique=False)
    op.create_table('sequence_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sequence_id', sa.String(length=36), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('delay_hours', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sequence_steps_sequence_id'), 'sequence_steps', ['sequence_id'], unique=False)
    op.create_table('email_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('sequence_id', sa.String(length=36), nullable=True),
    sa.Column('sequence_step_id', sa.String(length=36), nullable=True),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequences.id'], ),
    sa.ForeignKeyConstraint(['sequence_step_id'], ['sequence_steps.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_messages_lead_id'), 'email_messages', ['lead_id'], unique=False)
    op.create_index(op.f('ix_email_messages_provider_message_id'), 'email_messages', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_email_messages_workspace_id'), 'email_messages', ['workspace_id'], unique=False)
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webhook_token', sa.String(length=64), nullable=False, server_default=''))
        batch_op.create_unique_constraint('uq_workspaces_webhook_token', ['webhook_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_constraint('uq_workspaces_webhook_token', type_='unique')
        batch_op.drop_column('webhook_token')
    op.drop_index(op.f('ix_email_messages_workspace_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_provider_message_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_lead_id'), table_name='email_messages')
    op.drop_table('email_messages')
    op.drop_index(op.f('ix_sequence_steps_sequence_id'), table_name='sequence_steps')
    op.drop_table('sequence_steps')
    op.drop_index(op.f('ix_sequences_workspace_id'), table_name='sequences')
    op.drop_table('sequences')
    # ### end Alembic commands ###
