"""Niche synonym engine — expand one user niche into the search terms that
actually surface results in different markets.

A single niche ("dentist", "plumber") is understood differently around the
world: US directories say "dental clinic", the UK says "dental practice",
Russia's Yandex catalogs under "Стоматология", and aggregators like BizData
use machine slugs ("beauty salon"). Rather than hard-code every directory's
vocabulary into each crawler, this module exposes the common English-market
variants plus the niche->aggregator-category map so every crawler and the
exact-count fill ladder can fan out to real synonyms instead of repeating one
stale term that a source no longer indexes.
"""
import re

# niche keyword -> list of equivalent search phrases (first = the term the
# widest set of directories/engines recognizes). Everything here is English;
# the crawlers themselves may localize later, but a broad English synonym set
# already fixes most thin-result cases across the worldwide directories.
_NICHE_SYNONYMS: dict[str, list[str]] = {
    "dentist": ["dentist", "dental clinic", "dental practice", "dental care", "dentist office"],
    "dental": ["dental clinic", "dentist", "dental practice", "dental care"],
    "doctor": ["doctor", "physician", "medical clinic", "general practice", "medical center"],
    "hospital": ["hospital", "medical center", "healthcare center", "clinic hospital"],
    "clinic": ["clinic", "medical clinic", "health clinic", "urgent care"],
    "pharmac": ["pharmacy", "chemist", "drug store", "pharmacist"],
    "restaurant": ["restaurant", "dining", "eatery", "food place", "restaurant dining"],
    "cafe": ["cafe", "coffee shop", "coffee house", "café"],
    "coffee": ["coffee shop", "cafe", "coffee house", "espresso bar"],
    "hotel": ["hotel", "lodging", "inn", "accommodation", "hotel resort"],
    "gym": ["gym", "fitness center", "fitness club", "health club", "workout center"],
    "beauty": ["beauty salon", "beauty parlor", "hair salon", "beauty clinic", "spa salon"],
    "salon": ["salon", "hair salon", "beauty salon", "barbershop"],
    "plumber": ["plumber", "plumbing", "plumbing service", "plumbing contractor"],
    "electrician": ["electrician", "electrical contractor", "electrical services", "electrician services"],
    "lawyer": ["lawyer", "law firm", "attorney", "legal services", "law office"],
    "attorney": ["attorney", "law firm", "lawyer", "legal services"],
    "accountant": ["accountant", "accounting firm", "tax advisor", "accounting services", "bookkeeping"],
    "real estate": ["real estate agency", "real estate", "realtor", "property agency", "estate agent"],
    "agency": ["agency", "marketing agency", "advertising agency", "digital agency"],
    "school": ["school", "academy", "school academy", "education center", "training center"],
    "college": ["college", "college academy", "educational institute", "higher education"],
    "university": ["university", "college university", "institute", "higher education"],
    "supermarket": ["supermarket", "grocery store", "grocery supermarket", "food market"],
    "grocery": ["grocery store", "supermarket", "grocery supermarket", "market"],
    "bakery": ["bakery", "baker shop", "bread shop", "patisserie"],
    "bank": ["bank", "banking", "bank branch", "financial institution"],
    "store": ["store", "shop", "retail store", "outlet"],
    "shop": ["shop", "store", "retail store", "outlet"],
    "car": ["car dealer", "car dealership", "automobile dealer", "car sales"],
    "auto": ["auto repair", "car repair", "automotive service", "garage", "auto service"],
    "repair": ["repair shop", "repair service", "repair store", "mobile repair"],
    "laundry": ["laundry", "laundromat", "dry cleaning", "dry cleaners"],
    "barber": ["barber", "barbershop", "hair cut", "barber shop"],
    "tattoo": ["tattoo studio", "tattoo shop", "tattoo parlor"],
    "photographer": ["photographer", "photography studio", "photo studio", "photography"],
    "travel": ["travel agency", "travel agent", "tour operator", "travel service"],
    "insurance": ["insurance", "insurance agency", "insurance broker", "insurance company"],
    "home": ["home improvement", "home repair", "home services", "home remodeling"],
    "cleaning": ["cleaning service", "house cleaning", "janitorial service", "cleaning company"],
    "pest": ["pest control", "pest exterminator", "pest management", "exterminator"],
    "painting": ["painting service", "paint contractor", "painter", "house painting"],
    "landscaping": ["landscaping", "landscape service", "lawn care", "garden service"],
    "moving": ["moving company", "movers", "moving service", "removal company"],
    "security": ["security company", "security services", "security guard", "security system"],
    "logistics": ["logistics", "freight", "shipping company", "transport logistics", "courier"],
    "courier": ["courier", "courier service", "delivery service", "parcel delivery"],
    "realestate": ["real estate agency", "real estate", "realtor"],
    "property": ["property management", "real estate", "property agency"],
    "it": ["it services", "computer repair", "it company", "software company", "tech services"],
    "computer": ["computer repair", "computer services", "it services", "computer store"],
    "web": ["web design", "website design", "web development", "digital agency"],
    "digital": ["digital marketing", "digital agency", "seo services", "marketing agency"],
    "marketing": ["marketing agency", "digital marketing", "marketing company", "seo"],
    "seo": ["seo services", "search engine optimization", "digital marketing"],
    "law firm": ["law firm", "attorney", "lawyer", "legal services"],
    "architect": ["architect", "architecture firm", "architectural services"],
    "engineering": ["engineering", "engineering firm", "engineering company", "engineering services"],
    "construction": ["construction company", "builder", "construction services", "contractor"],
    "contractor": ["contractor", "general contractor", "construction company", "handyman"],
    "handyman": ["handyman", "home repair", "handyman services"],
    "pet": ["pet groomer", "pet shop", "veterinary clinic", "pet store", "pet care"],
    "veterinary": ["veterinary clinic", "veterinarian", "animal hospital", "vet"],
    "vet": ["veterinarian", "veterinary clinic", "animal hospital"],
    "fitness": ["fitness center", "gym", "fitness club", "fitness trainer"],
    "yoga": ["yoga studio", "yoga classes", "yoga center"],
    "hair": ["hair salon", "hair dresser", "salon", "hair styling"],
    "nail": ["nail salon", "nail studio", "manicure pedicure", "nail spa"],
    "spa": ["spa", "day spa", "spa salon", "wellness spa"],
    "massage": ["massage", "massage therapy", "massage therapist", "spa massage"],
    "jewelry": ["jewelry store", "jewellery shop", "jewelers", "gold shop"],
    "furniture": ["furniture store", "furniture shop", "home furniture", "furniture warehouse"],
    "electronics": ["electronics store", "electronics shop", "electronic repair", "appliance store"],
    "optometrist": ["optometrist", "eye clinic", "optician", "eye care"],
    "optician": ["optician", "optometrist", "eye care", "eyewear store"],
    "physiotherapist": ["physiotherapist", "physiotherapy", "physical therapy", "physio clinic"],
    "chiropractor": ["chiropractor", "chiropractic", "chiropractic clinic"],
    "psychologist": ["psychologist", "psychology clinic", "therapist", "counseling"],
    "dermatologist": ["dermatologist", "skin clinic", "dermatology", "skin care clinic"],
    "gynecologist": ["gynecologist", "gynecology clinic", "women's clinic"],
    "pediatrician": ["pediatrician", "pediatric clinic", "children's doctor", "pediatrics"],
    "nutritionist": ["nutritionist", "nutrition", "dietitian", "nutrition clinic"],
    "pharmacy": ["pharmacy", "chemist", "drug store"],
    "clinic cosmetic": ["cosmetic clinic", "beauty clinic", "aesthetic clinic"],
    "optic": ["optician", "optometrist", "eye care", "optical store"],
    "travel agent": ["travel agency", "travel agent", "tour operator"],
    "wedding": ["wedding planner", "wedding venue", "wedding photography", "bridal"],
    "event": ["event planner", "event management", "event organizer", "event company"],
    "catering": ["catering", "catering service", "caterer", "event catering"],
    "real estate agent": ["real estate agency", "realtor", "real estate"],
    "childcare": ["childcare", "daycare", "child care", "preschool"],
    "preschool": ["preschool", "daycare", "kindergarten", "childcare"],
    "translation": ["translation services", "translator", "translation agency"],
    "printing": ["printing services", "print shop", "printing press", "printing company"],
    "auto repair": ["auto repair", "car repair", "automotive service", "garage"],
    "mechanic": ["mechanic", "auto repair", "car service", "garage"],
    "tire": ["tire shop", "tyre shop", "tire store", "tire service"],
    "gas station": ["gas station", "petrol station", "fuel station", "petrol pump"],
    "florist": ["florist", "flower shop", "floral shop", "flower delivery"],
    "book": ["bookstore", "book shop", "library bookshop", "books store"],
    "game": ["game store", "video game store", "game shop"],
    "clothing": ["clothing store", "clothes shop", "fashion store", "apparel store"],
    "shoe": ["shoe store", "shoe shop", "footwear store"],
    "bakery cafe": ["bakery cafe", "cafe bakery", "bakery", "coffee bakery"],
    "restaurant fast food": ["fast food", "fast food restaurant", "quick service restaurant", "takeaway"],
    "pizza": ["pizza", "pizza restaurant", "pizza place", "pizzeria"],
    "burger": ["burger", "burger restaurant", "burger joint", "fast food"],
    "barbecue": ["barbecue", "bbq", "bbq restaurant", "barbecue restaurant"],
    "seafood": ["seafood", "seafood restaurant", "fish restaurant"],
    "chinese": ["chinese restaurant", "chinese food", "chinese takeaway"],
    "indian": ["indian restaurant", "indian food", "indian takeaway"],
    "italian": ["italian restaurant", "italian food", "trattoria", "pizzeria"],
    "bakery bakery": ["bakery", "bread shop"],
    "ice cream": ["ice cream shop", "ice cream parlor", "gelato", "dessert shop"],
    "juice": ["juice bar", "juice shop", "smoothie bar", "juice corner"],
    "coffee shop": ["coffee shop", "cafe", "coffee house"],
    "grocery store": ["grocery store", "supermarket", "grocery market"],
    "convenience": ["convenience store", "corner store", "general store", "c-store"],
    "hardware": ["hardware store", "home improvement store", "hardware shop"],
    "electronics repair": ["electronics repair", "phone repair", "mobile repair", "computer repair"],
    "phone": ["phone repair", "mobile phone shop", "mobile store", "phone store"],
    "mobile": ["mobile phone shop", "mobile store", "phone repair", "mobile shop"],
    "air conditioning": ["air conditioning", "ac repair", "hvac", "air conditioner service"],
    "hvac": ["hvac", "heating cooling", "air conditioning", "ac repair"],
    "roofing": ["roofing", "roofing contractor", "roof repair"],
    "flooring": ["flooring", "flooring contractor", "tile flooring"],
    "glass": ["glass company", "glass repair", "glass service", "glass shop"],
    "doors": ["doors windows", "door company", "window installation", "door installation"],
    "window": ["windows installation", "window company", "doors windows"],
    "solar": ["solar energy", "solar panel", "solar installation", "solar company"],
    "generator": ["generator", "generator repair", "generator service", "power generator"],
    "electrician near": ["electrician", "electrical services"],
    "locksmith": ["locksmith", "lock and key", "lockout service", "key services"],
    "garden": ["garden service", "landscaping", "garden maintenance", "gardening"],
    "pool": ["pool service", "swimming pool", "pool cleaning", "pool maintenance"],
    "tutoring": ["tutoring", "tuition center", "tutor", "academy"],
    "training": ["training center", "training institute", "skills training", "academy"],
    "language": ["language school", "language institute", "language classes", "english academy"],
    "music": ["music school", "music academy", "music lessons", "music studio"],
    "dance": ["dance studio", "dance classes", "dance academy"],
    "art": ["art studio", "art school", "art gallery", "art classes"],
    "photography": ["photography studio", "photographer", "photo studio"],
    "video": ["video production", "video editing", "videography", "media production"],
    "film": ["film production", "video production", "media company"],
    "advertising": ["advertising agency", "ad agency", "marketing agency"],
    "public relations": ["public relations", "pr agency", "pr firm"],
    "consulting": ["consulting", "consultancy", "business consultant", "consulting firm"],
    "hr": ["hr services", "human resources", "recruitment agency", "staffing"],
    "recruitment": ["recruitment agency", "recruiter", "staffing agency", "placement agency"],
    "staffing": ["staffing agency", "recruitment agency", "employment agency"],
    "facility": ["facility management", "facilities management", "janitorial"],
    "office": ["office supplies", "office furniture", "office equipment", "stationery"],
    "stationery": ["stationery", "office supplies", "stationery store"],
    "medical": ["medical clinic", "medical center", "medical services", "healthcare clinic"],
    "healthcare": ["healthcare services", "medical center", "healthcare clinic", "health services"],
    "dental care": ["dental clinic", "dentist", "dental practice"],
    "skin": ["skin clinic", "dermatology", "skin care", "aesthetic clinic"],
    "hair removal": ["laser hair removal", "hair removal", "aesthetic clinic"],
    "aesthetic": ["aesthetic clinic", "cosmetic clinic", "beauty clinic"],
    "cosmetic": ["cosmetic clinic", "aesthetic clinic", "cosmetic surgery"],
    "diet": ["dietitian", "nutritionist", "nutrition clinic"],
    "physical therapy": ["physical therapy", "physiotherapy", "rehab clinic"],
    "rehab": ["rehabilitation center", "physical therapy", "rehab clinic"],
    "dental lab": ["dental lab", "dental laboratory"],
    "realty": ["real estate agency", "realtor", "real estate"],
    "tours": ["tour operator", "travel agency", "tour company"],
    "cargo": ["cargo", "freight forwarding", "shipping company", "logistics"],
    "freight": ["freight", "freight forwarding", "shipping", "logistics"],
    "packers": ["packers and movers", "moving company", "movers", "packing moving"],
    "movers": ["movers", "moving company", "packers and movers"],
    "auto parts": ["auto parts", "car parts", "auto accessories", "spare parts"],
    "spare": ["spare parts", "auto parts", "spare parts store"],
    "bike": ["motorcycle", "bike shop", "motorcycle repair", "bike service"],
    "motorcycle": ["motorcycle", "bike shop", "motorcycle dealer", "bike repair"],
    "taxi": ["taxi service", "cab service", "taxi company", "car rental"],
    "car rental": ["car rental", "car hire", "rent a car"],
    "bus": ["bus service", "bus travel", "bus company"],
    "shipping": ["shipping company", "courier", "logistics", "freight"],
    "packing": ["packing services", "packers and movers", "packaging company"],
    "gold": ["gold jewelry", "gold shop", "jewelry store", "gold smith"],
    "silver": ["silver jewelry", "jewelry store", "silver shop"],
    "watch": ["watch store", "watch repair", "watches", "jewelry watch"],
    "sunglasses": ["sunglasses store", "optical store", "eyewear"],
    "cosmetics": ["cosmetics store", "beauty supply", "cosmetics shop", "makeup store"],
    "perfume": ["perfume shop", "perfumery", "fragrance store"],
    "gift": ["gift shop", "gift store", "gift boutique", "gifts"],
    "toy": ["toy store", "toys shop", "toy shop"],
    "sports": ["sports store", "sports shop", "sporting goods", "sports equipment"],
    "apparel": ["clothing store", "apparel store", "fashion store"],
    "textile": ["textile", "fabric store", "textile company"],
    "carpet": ["carpet store", "carpet cleaning", "rug store"],
    "curtain": ["curtains", "curtain store", "window treatments"],
    "home decor": ["home decor", "home furnishings", "interior design", "decor store"],
    "interior": ["interior design", "interior decorator", "interior designer", "home decor"],
    "painting service": ["painting services", "painter", "paint contractor"],
    "tiles": ["tiles", "tile store", "tile flooring"],
    "marble": ["marble", "marble supplier", "stone supplier", "granite"],
    "granite": ["granite", "countertop", "stone supplier"],
    "kitchen": ["kitchen cabinets", "kitchen remodeling", "kitchen design"],
    "bathroom": ["bathroom remodeling", "bathroom fixtures", "bath remodeling"],
    "ac repair": ["ac repair", "air conditioning", "ac service"],
    "refrigeration": ["refrigeration", "refrigerator repair", "cold storage"],
    "appliance": ["appliance repair", "appliance store", "home appliance"],
    "furniture repair": ["furniture repair", "furniture restoration"],
    "upholstery": ["upholstery", "upholstery service", "furniture upholstery"],
    "tailor": ["tailor", "tailoring", "tailor shop", "bespoke tailor"],
    "alteration": ["alterations", "tailoring", "garment alteration"],
    "dry cleaners": ["dry cleaning", "dry cleaners", "laundry"],
    "car wash": ["car wash", "auto wash", "car detailing"],
    "car detailing": ["car detailing", "auto detailing", "car detail"],
    "towing": ["towing", "tow truck", "towing service"],
    "emergency": ["emergency services", "emergency repair", "24 hour"],
    "24 hour": ["24 hour", "24/7", "open now", "after hours"],
    "on site": ["mobile service", "on site service", "on call"],
    "on call": ["on call", "mobile service", "emergency"],
}


def expand_synonyms(niche: str) -> list[str]:
    """Return the ordered list of search phrases to try for a niche: the
    original term first, then its known synonyms. Always returns at least the
    original so unknown niches still work verbatim."""
    lowered = (niche or "").strip().lower()
    if not lowered:
        return []
    candidates = _NICHE_SYNONYMS.get(lowered) or []
    deduped: list[str] = []
    seen: set[str] = set()
    for term in [lowered, *candidates]:
        if term not in seen:
            seen.add(term)
            deduped.append(term)
    return deduped


def canonical_category(niche: str) -> str:
    """Best-effort canonical category slug (for aggregators like BizData that
    catalog by fixed categories). Returns '' when the niche is too specific."""
    lowered = (niche or "").strip().lower()
    for keyword, synonyms in _NICHE_SYNONYMS.items():
        if keyword == lowered:
            first = re.sub(r"[^a-z0-9]+", " ", synonyms[0]).strip()
            return " ".join(first.split())
    return ""
